source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "puma", "~> 6.0"
gem "rack-contrib", "~> 2.4"
gem "rackup", "~> 2.1"

group :test do
  gem "minitest", "~> 5.0"
  gem "rack-test", "~> 2.1"
end
